# This is a basic workflow to help you get started with Actions

name: Azure storage update

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Upload html to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name "timestablesapp" --auth-mode key -d '$web' -s . --pattern *.html
      - name: Upload assets to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name "timestablesapp" --auth-mode key -d '$web' -s . --pattern "timestables.*"
      - name: Purge Azure CDN
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths "/*" --profile-name "TimestablesappCDN" --name "timestablesapp" --resource-group "Default-Storage-WestEurope" 
      - name: logout
        run: |
          az logout
        if: always()
        
