# This is a basic workflow to help you get started with Actions

name: Main - Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Resolve git variables
        id: vars
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
          echo "commit_date=$(git show --no-patch --no-notes --pretty='%cd' "$GITHUB_SHA")" >> $GITHUB_ENV
          echo "branch_name=$GITHUB_REF_NAME" >> $GITHUB_ENV

      - name: Replace git variables
        shell: bash
        run: |
          sed -i 's/{commitId}/${{ env.sha_short }}/g' index.html
          sed -i 's/{commitTime}/${{ env.commit_date }}/g' index.html
          sed -i 's/{branchName}/${{ env.branch_name }}/g' index.html
        
      - name: Upload html to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name "timestablesapp" --auth-mode key -d '$web' -s . --pattern *.html
      - name: Upload js to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name "timestablesapp" --auth-mode key -d '$web' -s . --pattern "*.js"
      - name: Upload css to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name "timestablesapp" --auth-mode key -d '$web' -s . --pattern "*.css"

      - name: Purge Azure CDN
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths "/*" --profile-name "TimestablesappCDN" --name "timestablesapp" --resource-group "Default-Storage-WestEurope" 
      - name: logout
        run: |
          az logout
        if: always()
        
