name: Remove deployment

on:
  workflow_dispatch:
    inputs:
      deployment_dir:
        description: 'Deployment directory'
        require: true
        type: string
        default: ''
  pull_request:
    types: [closed]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Resolve deployment variables
        shell: bash
        if: ${{ github.event.inputs.deployment_dir == '' }}
        run: |
          echo "deployment_dir=${{ github.event.pull_request.number }}_merge" >> $GITHUB_ENV

      - name: Resolve deployment variables
        shell: bash
        run: |
          echo "deploy_dir_relative=${{ env.deployment_dir }}" >> $GITHUB_ENV

      - name: Setup azure cli (install extensions without a prompt)
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt

      - name: Delete current deployment directory
        uses: azure/CLI@v1
        if: ${{ env.deploy_dir_relative != 'main' }}
        with:
          inlineScript: |
            az storage blob directory delete --account-name "timestablesapp" --auth-mode key -d $deploy_dir_relative -c '$web' --recursive

      - name: logout
        run: |
          az logout
        if: always()

